export const mockPatient = {
  age: 42,
  shareNotes: true,
  hasActiveSubscription: false,
  previousMedicines: [],
  preventiveMedicines: [],
  medicines: [
    {
      id: 938,
      name: "Paracetamol",
      atcCode: "N02BE01",
      ingredients: ["PARACETAMOL_"],
    },
  ],
  scores: {
    "2025-12-01": 2,
    "2026-01-01": 3,
    "2026-02-01": 16,
    "2026-03-01": 5,
  },
  questionnaires: [],
  advice: [],
  records: [
    {
      date: "2026-02-02",
      intensity: 4,
      effect: 2,
      period: 4,
      emotion: 3,
      endoBelly: 4,
      bowelMovementPain: 5,
      urinationPain: 3,
      fatigue: 4,
      stress: 3,
      absentWork: 2,
      absentSocial: 2,
      sexualPain: 4,
      sexualPrevented: 2,
      physicalActivity: 120,
      sleepHours: 7,
      sleepQuality: 2,
      note: "hei",
      acuteMedicines: [938],
      acuteMedicinesAtc: ["N02BE01"],
      acuteMedicinesDoses: [1000],
      acuteMedicinesUsedTimes: [2],
    },
    {
      date: "2026-02-15",
      intensity: 5,
      effect: 2,
      period: 5,
      emotion: 3,
      endoBelly: 5,
      bowelMovementPain: 5,
      urinationPain: 5,
      fatigue: 5,
      stress: 4,
      absentWork: 3,
      absentSocial: 3,
      sexualPain: 4,
      sexualPrevented: 2,
      physicalActivity: 150,
      sleepHours: 10,
      sleepQuality: 3,
      note: "Flo",
      acuteMedicines: [938],
      acuteMedicinesAtc: ["N02BE01"],
      acuteMedicinesDoses: [1000],
      acuteMedicinesUsedTimes: [2],
    },
  ],
};
